apiVersion: v1
kind: ServiceAccount
metadata:
  name: erp-odoo
  namespace: "default"
  labels:
    app.kubernetes.io/instance: erp
    app.kubernetes.io/name: odoo
automountServiceAccountToken: false
secrets:
  - name: erp-odoo