apiVersion: v1
kind: Secret
metadata:
  name: my-release-odoo
  namespace: "default"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: odoo
type: Opaque
data:
  odoo-password: "TVBDbWFySVA1dg=="